name: restaurants-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      -master
  workflow_dispatch:


jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v4.3.0
       with: 
           dotnet-version: '8.0.x || 9.0.x'

     - name: Set up connection string for testing
       run: echo "ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION }}" >> $GITHUB_ENV     
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test
    
